config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'welcome/index'
  get 'welcome/update_cities', as: 'update_cities'
  get 'welcome/show'
  get 'welcome/mlb'
  root 'welcome#home'

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  as :user do
    get 'welcome/index', :to => 'devise/registrations#edit', :as => :user_root
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout false, only: [:home]

  def home

  end






  def index
    @countries = Country.all
    @cities = City.where("country_id = ?", Country.first.id)
    @user = current_user
  end

  def show
    @country = Country.find_by("id = ?", params[:trip][:country_id])
    @city = City.find_by("id = ?", params[:trip][:city_id])
    @user = current_user
    @user.team = @city.name
    @user.league = @country.name
    @user.save
  end

  def update_cities
    @cities = City.where("country_id = ?", params[:country_id])
    respond_to do |format|
      format.js
    end
  end



end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamecrunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header page-scroll">


      <%= link_to "GAMECRUNCH", root_url, id: 'logo' %>

    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_url %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      </ul>

    </div>
  </div>

</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<div>
 <div class="jumbotron"></div>

 <div class="row">

  <div class="col-md-5">
  </div>

  <div class="col-md-4">
    </br>
    <button type="button" class="btn btn-default btn-lg" style="color: #ffff00; background: darkslategrey">
      <%= link_to "Sign Up Now!", new_phone_number_path, method: :get, style: 'color:#ffff00' %></button>
  </div>

 </div>

</div>

</body>

app/views/welcome/index.html.erb
<% if @user.team.blank? %>
      <h3>You're not following a team</h3>
<% else %>
    <h3>You're team is <%= @user.team %></h3>
<% end %>


<h5>Change Team:</h5>
<%= form_for :trip, url: {action: "show"}, html: {method: "get"} do |f| %>
    <%= f.select :country_id, options_for_select(@countries.collect { |country|
      [country.name.titleize, country.id] }, 1), {}, { id: 'countries_select' } %>
    <%= f.select :city_id, options_for_select(@cities.collect { |city|
      [city.name.titleize, city.id] }, 0), {}, { id: 'cities_select' } %>
    <%= f.submit "Go!" %>


<% end %>

</br>
<% if @user.phone.blank? %>
    <h5>You haven't added a phone number! Please add one in 'Edit Info' below</h5>
    <% else %>
    <h5>Phone: </h5><%= @user.phone %>
<% end %>

</br></br>
<%= link_to 'Edit Info', edit_user_registration_path %>

app/views/welcome/mlb.html.erb
<h1>MLB</h1>


<ul>

  <li>hi</li>

  <% @mlbteams.each_pair do|key,value| %>
      <li><%= value %></li>
  <% end %>
</ul>

app/views/welcome/show.html.erb
<h5>Your new team is <%= @city.name.titleize %></h5>
<p><%= link_to 'Go Back', welcome_index_path %></p>