config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'welcome/index'
  get 'welcome/update_cities', as: 'update_cities'
  get 'welcome/show'
  get 'welcome/mlb'
  root 'welcome#home'

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  as :user do
    get 'welcome/index', :to => 'devise/registrations#edit', :as => :user_root
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base


  validates :phone_number, :length => { :is => 11 }

  def generate_pin
    self.pin = rand(0000..9999).to_s.rjust(4, "0")
    save
  end

  def twilio_client
  client = Twilio::REST::Client.new 'ACc37abcdd6d04384260291eb1f7075584', '8ef5aec33725886af6b1f9981bf86c0e'
  end

  def send_pin
    twilio_client.messages.create(
        to: phone_number,
        from: '14159172576',
        body: "Your PIN is #{pin}"
    )

      rescue Twilio::REST::RequestError => e
      File.open('public/twilio_error.txt', 'w') {|file| file.write(e.message)}
      raise

      save
  end

  def verify(entered_pin)
    if self.pin == entered_pin
      update(verified: true)
    end
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController


  def new
    @phone_number = PhoneNumber.new

    @read_file=File.open("public/twilio_error.txt").read


     if File.readlines("public/twilio_error.txt").size > 0
       logger.info "this iserror"
    flash[:notice] = @read_file
     render "new"
    end



  end

  def create
    @phone_number = PhoneNumber.find_or_create_by(phone_number: params[:phone_number][:phone_number])
    @phone_number.generate_pin
    @phone_number.send_pin
    respond_to do |format|
      format.js # render app/views/phone_numbers/create.js.erb
    end
  end

  def verify
    @phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])


    #write number to file bc i couldn't get it into the next controller with instance variable!!!
    cell = ''
    cell = params[:hidden_phone_number]
    File.open('public/cell.txt', 'w') {|file| file.write(cell)}


    if @phone_number.pin == (params[:pin2])
      @phone_number.verified = true

    respond_to do |format|
      format.js { render :js => "window.location = '/users/sign_up'"}
    end
      else
      @phone_number.verified  = false
      respond_to do |format|
        format.js

    end

    end

  end

end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/create.js.erb
$('#hidden_phone_number').val('<%= @phone_number.phone_number %>' )
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin2').focus()

app/views/phone_numbers/new.html.erb
</br>
<div id="send-pin">
  <h4>What's your phone number?</h4>
  <em>(add 1 + area code w/ no spaces; i.e. 15555555555)</em><br/>
  <%= form_for @phone_number, remote: true do |f| %>
      <%= f.error_messages %>
      <div class="form-group">
        <%= f.text_field :phone_number %>

      </div>
      <%= f.submit "Send PIN", class: "btn btn-primary", id: 'send-pin-link' %>
  <% end %>



</div>


<div id="verify-pin">
  <h4>Enter your PIN</h4>
  <%= form_tag phone_numbers_verify_path, remote: true do |f| %>
      <%= hidden_field_tag 'hidden_phone_number', '' %>
      <div class="form-group">
        <%= text_field_tag :pin2 %>
      </div>
      <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>

<div id="status-box" class="alert alert-success">
  <p id="status-message">Status: Haven’t done anything yet</p>
</div>

app/views/phone_numbers/verify.js.erb
<% if @phone_number.verified %>
$('#verify-pin').hide()
$('#status-box').removeClass()
$('#status-box').addClass('alert alert-success')
$('#status-message').text('Success!!')

<% else %>
$('#status-box').removeClass()
$('#status-box').addClass('alert alert-warning')
$('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()